[package]
name = "ifish"
version = "0.1.0"
authors = ["usiegl00 <50933431+usiegl00@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
